name: Deploy to Azure Gov new App Service & plan
#1 

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login (Azure Gov)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: AzureUSGovernment

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./application/single_app
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Optional: run tests here

      # Create new resource group in US Gov Arizona
      - name: Create new Resource Group (US Gov Arizona)
        run: |
          az group create --name ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} --location "usgovarizona"

      # Create new App Service Plan (P0v3) in new resource group
      - name: Create new App Service Plan (P0v3)
        run: |
          az appservice plan create \
            --name ${{ secrets.AZURE_NEW_APP_SERVICE_PLAN }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --sku P0v3 \
            --is-linux

      # Create Web App if not exists (use new app service plan and resource group)
      - name: Create Web App if not exists
        run: |
          az webapp create \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --plan ${{ secrets.AZURE_NEW_APP_SERVICE_PLAN }} \
            --name ${{ secrets.AZURE_NEW_WEBAPP_NAME }} \
            --runtime "PYTHON|3.12" || true

      # Set custom environment variables
      - name: Set App Service environment variables
        run: |
          az webapp config appsettings set \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_NEW_WEBAPP_NAME }} \
            --settings \
              AZURE_COSMOS_AUTHENTICATION_TYPE=${{ secrets.AZURE_COSMOS_AUTHENTICATION_TYPE }} \
              AZURE_COSMOS_ENDPOINT=${{ secrets.AZURE_COSMOS_ENDPOINT }} \
              AZURE_COSMOS_KEY=${{ secrets.AZURE_COSMOS_KEY }} \
              AZURE_ENVIRONMENT=${{ secrets.AZURE_ENVIRONMENT }} \
              CLIENT_ID=${{ secrets.CLIENT_ID }} \
              MICROSOFT_PROVIDER_AUTHENTICATION_SECRET=${{ secrets.MICROSOFT_PROVIDER_AUTHENTICATION_SECRET }} \
              SCM_DO_BUILD_DURING_DEPLOYMENT=${{ secrets.SCM_DO_BUILD_DURING_DEPLOYMENT }} \
              SECRET_KEY=${{ secrets.SECRET_KEY }} \
              TENANT_ID=${{ secrets.TENANT_ID }} \
              WEBSITE_AUTH_AAD_ALLOWED_TENANTS=${{ secrets.WEBSITE_AUTH_AAD_ALLOWED_TENANTS }}

      - name: Archive app for deployment
        working-directory: ./application/single_app
        run: |
          zip -r ../../webapp.zip . -x .dockerignore Dockerfile example_advance_edit_environment_variables.json example.env

      - name: Deploy .zip to Azure Gov App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_NEW_WEBAPP_NAME }}
          package: webapp.zip

