name: Deploy to Azure Gov SC Inra & Code #a

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login (Azure Gov)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: AzureUSGovernment

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./application/single_app
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Create new Resource Group (US Gov Arizona)
        run: |
          set -e
          az group create --name ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} --location "usgovarizona"

      - name: Create new Cosmos DB Account
        run: |
          set -e
          az cosmosdb create \
            --name ${{ secrets.AZURE_NEW_COSMOSDB_ACCOUNT }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --locations regionName="USGov Arizona" failoverPriority=0 isZoneRedundant=False \
            --default-consistency-level "Session" \
            --kind GlobalDocumentDB

      - name: Create new Cosmos DB SQL Database
        run: |
          set -e
          az cosmosdb sql database create \
            --account-name ${{ secrets.AZURE_NEW_COSMOSDB_ACCOUNT }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_NEW_COSMOSDB_DATABASE }}

      - name: Create Cosmos DB Containers
        run: |
          set -e
          for container in message settings groups group_prompt feedback archived_messages group_documents user_settings conversations documents file_processing archived_conversations safety; do
            az cosmosdb sql container create \
              --account-name ${{ secrets.AZURE_NEW_COSMOSDB_ACCOUNT }} \
              --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
              --database-name ${{ secrets.AZURE_NEW_COSMOSDB_DATABASE }} \
              --name $container \
              --partition-key-path "/id"
          done

      - name: Create new Document Intelligence Resource
        run: |
          set -e
          az cognitiveservices account create \
            --name ${{ secrets.AZURE_NEW_DOCINTEL_NAME }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --kind FormRecognizer \
            --sku S0 \
            --location "usgovarizona" \
            --yes

      - name: Create new AI Search Resource
        run: |
          set -e
          az search service create \
            --name ${{ secrets.AZURE_NEW_SEARCH_NAME }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --location "usgovarizona" \
            --sku basic

      - name: Create new Storage Account
        run: |
          set -e
          az storage account create \
            --name ${{ secrets.AZURE_NEW_STORAGE_ACCOUNT }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --location "usgovarizona" \
            --sku Standard_LRS \
            --kind StorageV2

      - name: Create new App Service Plan (P0v3)
        run: |
          set -e
          az appservice plan create \
            --name ${{ secrets.AZURE_NEW_APP_SERVICE_PLAN }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --sku P0v3 \
            --is-linux

      - name: Create Web App if not exists
        run: |
          set -e
          az webapp create \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --plan ${{ secrets.AZURE_NEW_APP_SERVICE_PLAN }} \
            --name ${{ secrets.AZURE_NEW_WEBAPP_NAME }} \
            --runtime "PYTHON|3.12" || true

      - name: Set App Service environment variables
        run: |
          set -e
          az webapp config appsettings set \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_NEW_WEBAPP_NAME }} \
            --settings \
              AZURE_COSMOS_AUTHENTICATION_TYPE=${{ secrets.AZURE_COSMOS_AUTHENTICATION_TYPE }} \
              AZURE_COSMOS_ENDPOINT=${{ secrets.AZURE_COSMOS_ENDPOINT }} \
              AZURE_COSMOS_KEY=${{ secrets.AZURE_COSMOS_KEY }} \
              AZURE_ENVIRONMENT=${{ secrets.AZURE_ENVIRONMENT }} \
              CLIENT_ID=${{ secrets.CLIENT_ID }} \
              MICROSOFT_PROVIDER_AUTHENTICATION_SECRET=${{ secrets.MICROSOFT_PROVIDER_AUTHENTICATION_SECRET }} \
              SCM_DO_BUILD_DURING_DEPLOYMENT=${{ secrets.SCM_DO_BUILD_DURING_DEPLOYMENT }} \
              SECRET_KEY=${{ secrets.SECRET_KEY }} \
              TENANT_ID=${{ secrets.TENANT_ID }} \
              WEBSITE_AUTH_AAD_ALLOWED_TENANTS=${{ secrets.WEBSITE_AUTH_AAD_ALLOWED_TENANTS }}

      - name: Archive app for deployment
        working-directory: ./application/single_app
        run: |
          zip -r ../../webapp.zip . -x .dockerignore Dockerfile example_advance_edit_environment_variables.json example.env

      - name: Deploy .zip to Azure Gov App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_NEW_WEBAPP_NAME }}
          package: webapp.zip

      - name: Create Azure OpenAI Resource
        run: |
          set -e
          az cognitiveservices account create \
            --name ${{ secrets.AZURE_NEW_OPENAI_NAME }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --kind OpenAI \
            --sku S0 \
            --location "usgovarizona" \
            --yes

      - name: Deploy OpenAI Models
        run: |
          set -e
          az cognitiveservices account deployment create \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_NEW_OPENAI_NAME }} \
            --deployment-name gpt-4o \
            --model-name gpt-4o \
            --model-version "2024-05-13" \
            --sku Standard \
            --model-format OpenAI \
            --capacity 1
          az cognitiveservices account deployment create \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_NEW_OPENAI_NAME }} \
            --deployment-name gpt-4o-mini \
            --model-name gpt-4o-mini \
            --model-version "2024-05-13" \
            --sku Standard \
            --model-format OpenAI \
            --capacity 1
          az cognitiveservices account deployment create \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_NEW_OPENAI_NAME }} \
            --deployment-name text-embedding-ada-002 \
            --model-name text-embedding-ada-002 \
            --model-version "2" \
            --sku Standard \
            --model-format OpenAI \
            --capacity 1

      - name: Output Cosmos DB and OpenAI endpoint and key to file
        run: |
          set -e
          COSMOS_ENDPOINT=$(az cosmosdb show \
            --name ${{ secrets.AZURE_NEW_COSMOSDB_ACCOUNT }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --query "documentEndpoint" -o tsv)
          COSMOS_KEY=$(az cosmosdb keys list \
            --name ${{ secrets.AZURE_NEW_COSMOSDB_ACCOUNT }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --query "primaryMasterKey" -o tsv)
          OPENAI_ENDPOINT=$(az cognitiveservices account show \
            --name ${{ secrets.AZURE_NEW_OPENAI_NAME }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --query "properties.endpoint" -o tsv)
          OPENAI_KEY=$(az cognitiveservices account keys list \
            --name ${{ secrets.AZURE_NEW_OPENAI_NAME }} \
            --resource-group ${{ secrets.AZURE_NEW_RESOURCE_GROUP }} \
            --query "key1" -o tsv)
          echo "COSMOS_ENDPOINT=$COSMOS_ENDPOINT" > resource_output.env
          echo "COSMOS_KEY=$COSMOS_KEY" >> resource_output.env
          echo "OPENAI_ENDPOINT=$OPENAI_ENDPOINT" >> resource_output.env
          echo "OPENAI_KEY=$OPENAI_KEY" >> resource_output.env
          cat resource_output.env

      - name: Upload Cosmos output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resource-output
          path: resource_output.env

