stages:
  - build
  - deploy

variables:
  AZURE_CLI_DISABLE_CONNECTION_VERIFICATION: 1

before_script:
  - apt-get update && apt-get install -y curl unzip
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az version

build:
  stage: build
  image: python:3.12
  script:
    - cd application/single_app
    - python -m pip install --upgrade pip
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Optional: run tests here
    - zip -r ../../webapp.zip . -x .dockerignore Dockerfile example_advance_edit_environment_variables.json example.env
  artifacts:
    paths:
      - webapp.zip

deploy:
  stage: deploy
  image: python:3.12
  dependencies:
    - build
  script:
    # Azure CLI login
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    - az account set --subscription "$AZURE_SUBSCRIPTION_ID"
    # Deploy to Azure App Service slot
    - az webapp deployment source config-zip --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_WEBAPP_NAME" --src webapp.zip --slot "$AZURE_WEBAPP_SLOT_NAME"
  only:
    - main
